services:
  # Web Service
  - type: web
    name: medusaxd-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    region: oregon
    branch: main
    healthCheckPath: /api/status
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: medusaxd-postgres
          property: connectionString
      - key: REDIS_CONN_STRING
        fromService:
          type: redis
          name: medusaxd-redis
          property: connectionString
      - key: TZ
        value: UTC
      - key: ERROR_LOG_ENABLED
        value: "true"
      - key: STREAMING_TIMEOUT
        value: "120"
      - key: FORCE_STREAM_OPTION
        value: "true"
      - key: GET_MEDIA_TOKEN
        value: "true"
      - key: GET_MEDIA_TOKEN_NOT_STREAM
        value: "true"
      - key: UPDATE_TASK
        value: "true"
      - key: COHERE_SAFETY_SETTING
        value: "NONE"
      - key: GEMINI_VISION_MAX_IMAGE_NUM
        value: "16"
      - key: MAX_FILE_DOWNLOAD_MB
        value: "20"
      - key: AZURE_DEFAULT_API_VERSION
        value: "2025-04-01-preview"
      - key: NOTIFICATION_LIMIT_DURATION_MINUTE
        value: "10"
      - key: NOTIFY_LIMIT_COUNT
        value: "2"
      - key: GENERATE_DEFAULT_TOKEN
        value: "false"
      - key: DIFY_DEBUG
        value: "true"
      - key: SESSION_SECRET
        generateValue: true
      - key: CRYPTO_SECRET
        generateValue: true
      - key: SERVER_ADDRESS
        value: https://medusaxd-api.onrender.com  # Change this to your custom domain if you have one
      - key: SYSTEM_NAME
        value: "MedusaXD API"  # Customizable system name for branding
      - key: SYSTEM_DESCRIPTION
        value: "Next-generation AI gateway and asset management system"  # System description
      - key: SYSTEM_KEYWORDS
        value: "AI,API,Gateway,LLM,OpenAI,Claude,Gemini"  # SEO keywords
      - key: FOOTER_TEXT
        value: "Powered by MedusaXD API"  # Footer branding text

  # Redis Cache Service
  - type: redis
    name: medusaxd-redis
    plan: free  # Free tier: 25MB RAM, 50 connections, ephemeral storage
    # For production, consider: starter ($10/month, 256MB, persistent)
    region: oregon
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []  # Empty list allows access from all Render services

databases:
  # PostgreSQL Database (Updated 2025 Plans)
  - name: medusaxd-postgres
    databaseName: medusaxd_api
    user: medusaxd_user
    plan: free  # Free tier: 1GB storage, 30-day limit, 256MB RAM, 0.1 CPU
    # For production, consider: basic-1gb ($19/month) or pro-4gb ($55/month)
    region: oregon
    postgresMajorVersion: "15"
    # Note: Paid plans include point-in-time recovery and flexible storage scaling
